// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHeWYEMku8SATbnyX1BsgFOV3KXLqGZo',
    appId: '1:422344311338:web:d32596f31e74acb6533953',
    messagingSenderId: '422344311338',
    projectId: 'chatappflutter-8b585',
    authDomain: 'chatappflutter-8b585.firebaseapp.com',
    storageBucket: 'chatappflutter-8b585.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOnbN25KGcXvCwkPbE6Z2ZktInxmgkZ8I',
    appId: '1:422344311338:android:1afb282ab2037307533953',
    messagingSenderId: '422344311338',
    projectId: 'chatappflutter-8b585',
    storageBucket: 'chatappflutter-8b585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWbX7RwdvzBrhiJCpGYls2OHZkhLAvpoc',
    appId: '1:422344311338:ios:66c50557a1559a0e533953',
    messagingSenderId: '422344311338',
    projectId: 'chatappflutter-8b585',
    storageBucket: 'chatappflutter-8b585.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
